inherit_from: https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - Guardfile
    - bin/**/*
    - config/application.rb
    - config/initializers/merit.rb
    - db/**/*
    - lib/tasks/get_classes_nj.rb
    - node_modules/**/*
    - app/models/ahoy/**/*

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Style/Encoding:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Exclude:
    - Gemfile
    - spec/**/*