inherit_from: https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - db/**/*
    - Guardfile

Layout/LineLength:
  Exclude:
    - bin/**/*
    - spec/**/*
    - config/initializers/devise.rb

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Style/MethodCallWithArgsParentheses:
  Exclude:
    - Gemfile
    - spec/**/*