language: ruby
rvm:
  - 2.6.3
services:
  - postgresql

cache: bundler
before_install:
  - gem install bundler
script:
  — bundle install
  — bundle exec rails db:test:prepare
  - bundle exec rspec spec