---
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: rjrobinson/soda-ruby-2.4.1-soda:latest
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          DB_HOST: 127.0.0.1
          DB_USER: root
          RAILS_ENV: test
          RACK_ENV: test
          DB_ADAPTER: postgresql
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: project-gru_test

    steps:
      - checkout

      - restore_cache:
          name: Restore Bundled Gems
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle

      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle

      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run rake:db:setup
          command: bundle exec rake db:setup

      - run:
          name: Run RSPEC spec
          command: |
            bundle exec rspec spec --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress

      - store_test_results:
          path: ~/tmp/test-results
      - store_artifacts:
          path: ~/repo/spec/rspec.xml

#      - run:
#          name: Run Brakeman
#          command: bundle exec brakeman --exit-on-warn > ~/repo/spec/brakeman.txt
#
#      - store_artifacts:
#          path: ~/repo/spec/brakeman.txt


workflows:
  version: 2
  gru_workflow:
    jobs:
      - build
#      - deploy-staging:
#          requires:
#            - build
#            - rspec
#            - brakeman
#          filters:
#            branches:
#              only: STAGING
#      - deploy-production:
#          requires:
#            - build
#            - rspec
#            - brakeman
#          filters:
#            branches:
#              only: PRODUCTION

deployment:
  production:
    branch: master
    heroku:
      appname: respondersnow