---
version: 2
jobs:
  build:
    working_directory: ~/respondersnow
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          PGHOST: localhost
          PGUSER: respondersnow
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: respondersnow
          POSTGRES_DB: respondersnow_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # install webkit
      - run:
          name: Install System Dependencies
          command: sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: respondersnow-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: respondersnow-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake