---
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: rjrobinson/resnow-ruby-2.6.3:latest
        environment:
          DB_USER: root
          RAILS_ENV: test
          RACK_ENV: test
          DB_ADAPTER: postgresql
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: project-gru_test

    steps:
      - checkout

      - restore_cache:
          name: Restore Bundled Gems
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle

      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle

      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run rake:db:setup
          command: bundle exec rake db:setup

      - store_test_results:
          path: ~/repo/spec

      - store_artifacts:
          path: ~/repo/spec/rspec.xml

      - run:
          name: Run RSPEC spec
          command: |
            bundle exec rspec spec --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress


workflows:
  version: 2
  resnow_pipeline:
    jobs:
      - build
#      - deploy-staging:
#          requires:
#            - build
#            - rspec
#            - brakeman
#          filters:
#            branches:
#              only: STAGING
#      - deploy-production:
#          requires:
#            - build
#            - rspec
#            - brakeman
#          filters:
#            branches:
#              only: PRODUCTION

deployment:
  production:
    branch: master
    heroku:
      appname: respondersnow