version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.1
      - image: postgres:9.5.1
        environment:
          POSTGRES_USER: root

    working_directory: /home/ubuntu/respondersnow
    steps:
      - checkout
      - run:
          name: Install capybara-webkit
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo apt-get install -y gcc g++ make qt5-default libqt5webkit5-dev ruby-dev zlib1g-dev

      - run: apt-get update -qq && apt-get install -y build-essential nodejs
      - run: bundle install
      - run: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test