---
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: responders_now_dev

test:
  <<: *default
  database: responders_now_test

production:
  <<: *default
  database: frn_production
  username: frn
  password: <%= ENV['FRN_DATABASE_PASSWORD'] %>
