test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws[:aws_access_key] %>
  secret_access_key: <%= Rails.application.credentials.aws[:aws_secret_key] %>
  region: <%= Rails.application.credentials.aws[:aws_region] %>
  bucket: "resnow-files"